# Python Libraries


In [1]:
ls = [1,2,3,4,5,6]

In [6]:
s = 0

for i in ls:
    print(s)
    s = s+i

0
1
3
6
10
15


In [7]:
s/len(ls)

3.5

In [8]:
len(ls)

6

In [9]:
float(len(ls))

6.0

In [10]:
sum(ls)

21

In [11]:
# Maximum element of the list

In [12]:
max(ls)

6

In [14]:
ls.count(2)

1

In [15]:
# libraries

In [16]:
import numpy

In [17]:
!pip install numpy

In [18]:
import pandas


In [19]:
import os

In [20]:
!pip install os

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os


# os

In [21]:
import os

In [22]:
dir(os)

['DirEntry',
 'F_OK',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_putenv',
 '_unsetenv',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen

In [24]:
os.listdir()

['.ipynb_checkpoints', 'Record.ipynb', 'Untitled.ipynb']

In [25]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.


In [26]:
pwd

'C:\\Users\\sahil\\Elite Techno Group'

# numpy

In [31]:
import numpy as np

In [27]:
numpy

<module 'numpy' from 'C:\\Users\\sahil\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [40]:
lst = [[1,2,3,9],[4,5,6,9],[7,8,9,9]]

In [41]:
type(lst)

list

In [42]:
np_array = numpy.array(lst)

In [43]:
np_array

array([[1, 2, 3, 9],
       [4, 5, 6, 9],
       [7, 8, 9, 9]])

In [44]:
np_array.shape

(3, 4)

In [45]:
np_array = np.reshape(np_array,(4,3))

In [46]:
np_array

array([[1, 2, 3],
       [9, 4, 5],
       [6, 9, 7],
       [8, 9, 9]])

In [47]:
np_array.shape

(4, 3)

In [48]:
# for specific shape

In [50]:
np.zeros((4,3), dtype = float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones((10,10), dtype = float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
rand = np.rand.randint(0,9)

print(rand)

In [ ]:
rand

In [ ]:
# checking the correct number

In [ ]:
num = 9 

n = input("Enter the number")

if(num == n):
    print("you win")
    
else:
    print("you lose")

In [ ]:
np.linespace(2,10,5)