# Numpy

In [1]:
import numpy as np

In [5]:
from numpy import random

In [11]:
rand = random.randint(0,9)

print(rand)

7


In [12]:
rand


7

In [13]:
np.linspace(2,10,7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [14]:
np.mean(np.linspace(2,10,9))

6.0

In [15]:
np.sqrt(np.linspace(2,10,9))

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766])

In [16]:
array = np.linspace(2,10,9)

In [17]:
array

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
array + 2

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [19]:
array - 2

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [20]:
array * 2


array([ 4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [21]:
array / 2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

# Pandas

In [22]:
import pandas as pd


In [23]:
! pip install pandas

In [24]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 10E7-B542

 Directory of C:\Users\sahil\Elite Techno Group

13-09-2021  15:16    <DIR>          .
13-09-2021  15:16    <DIR>          ..
13-09-2021  15:11    <DIR>          .ipynb_checkpoints
13-09-2021  15:10            15,057 python libraries 1.ipynb
13-09-2021  15:16             4,691 Python libraries 2.ipynb
07-09-2021  15:26            20,048 Record.ipynb
               3 File(s)         39,796 bytes
               3 Dir(s)  19,843,022,848 bytes free


In [25]:
ls


 Volume in drive C has no label.
 Volume Serial Number is 10E7-B542

 Directory of C:\Users\sahil\Elite Techno Group

13-09-2021  15:23    <DIR>          .
13-09-2021  15:23    <DIR>          ..
13-09-2021  15:11    <DIR>          .ipynb_checkpoints
13-09-2021  15:20            19,819 GOOG.csv
13-09-2021  15:10            15,057 python libraries 1.ipynb
13-09-2021  15:18             6,607 Python libraries 2.ipynb
07-09-2021  15:26            20,048 Record.ipynb
               4 File(s)         61,531 bytes
               3 Dir(s)  19,666,255,872 bytes free


In [28]:
df = pd.read_csv("GOOG.csv")

In [29]:
df

Date         Open         High          Low        Close  \
0    2020-09-14  1539.005005  1564.000000  1515.739990  1519.280029   
1    2020-09-15  1536.000000  1559.569946  1531.834961  1541.439941   
2    2020-09-16  1555.540039  1562.000000  1519.819946  1520.900024   
3    2020-09-17  1496.000000  1508.297974  1470.000000  1495.530029   
4    2020-09-18  1498.010010  1503.003052  1437.130005  1459.989990   
..          ...          ...          ...          ...          ...   
246  2021-09-03  2882.919922  2907.540039  2870.100098  2895.500000   
247  2021-09-07  2894.989990  2916.479980  2890.820068  2910.379883   
248  2021-09-08  2907.870117  2911.020020  2884.000000  2897.669922   
249  2021-09-09  2897.669922  2913.389893  2888.679932  2898.270020   
250  2021-09-10  2908.870117  2920.379883  2834.830078  2838.419922   

       Adj Close   Volume  
0    1519.280029  1696600  
1    1541.439941  1331100  
2    1520.900024  1311700  
3    1495.530029  1879800  
4    1459.989990  3103900  
..           ...      ...  
246  2895.500000   955200  
247  2910.379883   758500  
248  2897.669922   774300  
249  2898.270020   739900  
250  2838.419922  1643500  

[251 rows x 7 columns]

In [30]:
df.head()

Date         Open         High          Low        Close  \
0  2020-09-14  1539.005005  1564.000000  1515.739990  1519.280029   
1  2020-09-15  1536.000000  1559.569946  1531.834961  1541.439941   
2  2020-09-16  1555.540039  1562.000000  1519.819946  1520.900024   
3  2020-09-17  1496.000000  1508.297974  1470.000000  1495.530029   
4  2020-09-18  1498.010010  1503.003052  1437.130005  1459.989990   

     Adj Close   Volume  
0  1519.280029  1696600  
1  1541.439941  1331100  
2  1520.900024  1311700  
3  1495.530029  1879800  
4  1459.989990  3103900

In [31]:
df.head(0)

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume]
Index: []

In [33]:
df['Date']

0      2020-09-14
1      2020-09-15
2      2020-09-16
3      2020-09-17
4      2020-09-18
          ...    
246    2021-09-03
247    2021-09-07
248    2021-09-08
249    2021-09-09
250    2021-09-10
Name: Date, Length: 251, dtype: object

In [35]:
df['Date'].values

array(['2020-09-14', '2020-09-15', '2020-09-16', '2020-09-17',
       '2020-09-18', '2020-09-21', '2020-09-22', '2020-09-23',
       '2020-09-24', '2020-09-25', '2020-09-28', '2020-09-29',
       '2020-09-30', '2020-10-01', '2020-10-02', '2020-10-05',
       '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09',
       '2020-10-12', '2020-10-13', '2020-10-14', '2020-10-15',
       '2020-10-16', '2020-10-19', '2020-10-20', '2020-10-21',
       '2020-10-22', '2020-10-23', '2020-10-26', '2020-10-27',
       '2020-10-28', '2020-10-29', '2020-10-30', '2020-11-02',
       '2020-11-03', '2020-11-04', '2020-11-05', '2020-11-06',
       '2020-11-09', '2020-11-10', '2020-11-11', '2020-11-12',
       '2020-11-13', '2020-11-16', '2020-11-17', '2020-11-18',
       '2020-11-19', '2020-11-20', '2020-11-23', '2020-11-24',
       '2020-11-25', '2020-11-27', '2020-11-30', '2020-12-01',
       '2020-12-02', '2020-12-03', '2020-12-04', '2020-12-07',
       '2020-12-08', '2020-12-09', '2020-12-10', '2020-

In [36]:
df

Date         Open         High          Low        Close  \
0    2020-09-14  1539.005005  1564.000000  1515.739990  1519.280029   
1    2020-09-15  1536.000000  1559.569946  1531.834961  1541.439941   
2    2020-09-16  1555.540039  1562.000000  1519.819946  1520.900024   
3    2020-09-17  1496.000000  1508.297974  1470.000000  1495.530029   
4    2020-09-18  1498.010010  1503.003052  1437.130005  1459.989990   
..          ...          ...          ...          ...          ...   
246  2021-09-03  2882.919922  2907.540039  2870.100098  2895.500000   
247  2021-09-07  2894.989990  2916.479980  2890.820068  2910.379883   
248  2021-09-08  2907.870117  2911.020020  2884.000000  2897.669922   
249  2021-09-09  2897.669922  2913.389893  2888.679932  2898.270020   
250  2021-09-10  2908.870117  2920.379883  2834.830078  2838.419922   

       Adj Close   Volume  
0    1519.280029  1696600  
1    1541.439941  1331100  
2    1520.900024  1311700  
3    1495.530029  1879800  
4    1459.989990  3103900  
..           ...      ...  
246  2895.500000   955200  
247  2910.379883   758500  
248  2897.669922   774300  
249  2898.270020   739900  
250  2838.419922  1643500  

[251 rows x 7 columns]

In [37]:
data = df.values

In [38]:
data


array([['2020-09-14', 1539.005005, 1564.0, ..., 1519.280029, 1519.280029,
        1696600],
       ['2020-09-15', 1536.0, 1559.569946, ..., 1541.439941, 1541.439941,
        1331100],
       ['2020-09-16', 1555.540039, 1562.0, ..., 1520.900024, 1520.900024,
        1311700],
       ...,
       ['2021-09-08', 2907.8701170000004, 2911.02002, ..., 2897.669922,
        2897.669922, 774300],
       ['2021-09-09', 2897.669922, 2913.389893, ..., 2898.27002,
        2898.27002, 739900],
       ['2021-09-10', 2908.8701170000004, 2920.3798829999996, ...,
        2838.419922, 2838.419922, 1643500]], dtype=object)

In [39]:
data[:,:]

array([['2020-09-14', 1539.005005, 1564.0, ..., 1519.280029, 1519.280029,
        1696600],
       ['2020-09-15', 1536.0, 1559.569946, ..., 1541.439941, 1541.439941,
        1331100],
       ['2020-09-16', 1555.540039, 1562.0, ..., 1520.900024, 1520.900024,
        1311700],
       ...,
       ['2021-09-08', 2907.8701170000004, 2911.02002, ..., 2897.669922,
        2897.669922, 774300],
       ['2021-09-09', 2897.669922, 2913.389893, ..., 2898.27002,
        2898.27002, 739900],
       ['2021-09-10', 2908.8701170000004, 2920.3798829999996, ...,
        2838.419922, 2838.419922, 1643500]], dtype=object)

In [40]:
data[2: , :]

array([['2020-09-16', 1555.540039, 1562.0, ..., 1520.900024, 1520.900024,
        1311700],
       ['2020-09-17', 1496.0, 1508.297974, ..., 1495.530029, 1495.530029,
        1879800],
       ['2020-09-18', 1498.01001, 1503.003052, ..., 1459.98999,
        1459.98999, 3103900],
       ...,
       ['2021-09-08', 2907.8701170000004, 2911.02002, ..., 2897.669922,
        2897.669922, 774300],
       ['2021-09-09', 2897.669922, 2913.389893, ..., 2898.27002,
        2898.27002, 739900],
       ['2021-09-10', 2908.8701170000004, 2920.3798829999996, ...,
        2838.419922, 2838.419922, 1643500]], dtype=object)

In [41]:
data[: , 2:]

array([[1564.0, 1515.73999, 1519.280029, 1519.280029, 1696600],
       [1559.569946, 1531.834961, 1541.439941, 1541.439941, 1331100],
       [1562.0, 1519.819946, 1520.900024, 1520.900024, 1311700],
       ...,
       [2911.02002, 2884.0, 2897.669922, 2897.669922, 774300],
       [2913.389893, 2888.679932, 2898.27002, 2898.27002, 739900],
       [2920.3798829999996, 2834.830078, 2838.419922, 2838.419922,
        1643500]], dtype=object)

In [42]:
data[: , 2:3]

array([[1564.0],
       [1559.569946],
       [1562.0],
       [1508.297974],
       [1503.003052],
       [1448.359985],
       [1469.52002],
       [1460.959961],
       [1443.7089839999999],
       [1450.0],
       [1476.800049],
       [1476.662964],
       [1489.75],
       [1499.040039],
       [1483.199951],
       [1488.209961],
       [1486.76001],
       [1468.959961],
       [1490.0],
       [1516.52002],
       [1593.859985],
       [1590.0],
       [1587.68396],
       [1575.10498],
       [1581.130005],
       [1588.150024],
       [1577.5],
       [1618.72998],
       [1621.98999],
       [1642.359985],
       [1638.23999],
       [1606.844971],
       [1561.349976],
       [1593.709961],
       [1687.0],
       [1660.77002],
       [1661.699951],
       [1771.3649899999998],
       [1793.640015],
       [1772.430054],
       [1818.060059],
       [1763.0],
       [1764.219971],
       [1768.27002],
       [1781.040039],
       [1799.069946],
       [1785.0],
       [177

In [43]:
data[2:3 , 2:3]

array([[1562.0]], dtype=object)